export const SAGA_GET_CONTACT_LIST = "SAGA_GET_CONTACT_LIST"
export const SAGA_ADD_CONTACT = "SAGA_ADD_CONTACT"
export const SAGA_UPDATE_CONTACT = "SAGA_UPDATE_CONTACT"
export const SAGA_REMOVE_CONTACT = "SAGA_REMOVE_CONTACT"
